### ISSUE TITLE
Lockdrop issue - Metamask / Ledger Nano S

### ISSUE THREAD

**Issue by Majosk100** [staketechnologies/lockdrop-ui#140] opened 2020-09-12 10:10 UTC
Hi all, Im encountering issue when trying to lock eth. Error: TransportStatusError: ledger device: Invalid data received (0x6a80). Metamask error also pops up ("transaction 32 failed")Any ideas on how to solve this error?:

@Majosk  that is an odd error. Thank you for notifying the team. Can you open an issue on github regarding the error in detail so we can add that to our todo list? https://github.com/staketechnologies/lockdrop-ui/issues thanks

**Comment by Majosk100** [comment] 2020-09-12 10:27
I have resolved the issue by not using a ledger nano s account but Metamask instead, to lock eth. Seems to be a connecting error between Metamask and my ledger, and this only during transactions (balances etc. are up to date and correct)

**Comment by hoonsubin** [comment] 2020-09-12 10:30
@Majosk100 I'm glad that the issue has been solved. Just to be sure, I'll try to look into other measures we can take to improve the connection if the cause is from out page. For now, I'll close this issue, but if there are other problems, please feel free to comment on this thread.

**Closed by hoonsubin** 2020-09-12 10:30 UTC
Labels: bug

**Comment by Majosk100** [comment] 2020-09-12 12:27
Hi Hoonsubin, how long does it take to see claimed PLM in my account (the webwallet). Its been about an hour...
I've used metamask private key route to create my account and in the default claim address on the lockdrop page.

**Comment by hoonsubin** [comment] 2020-09-12 12:59
the process of claiming your tokens are; lock eth -> wait for about 2 minutes -> choose plasm net address to send to-> press the claim request button (blue arrow icon) -> wait for up to 10 minutes -> press the claim button (blue checkmark button).
If the real-time lockdrop claim status panel shows that you have completed the claim but it's not showing on your account, I suggest that you try to check your address balance via Subscan https://plasm.subscan.io/ to be sure.

**Comment by Majosk100** [comment] 2020-09-12 13:17
![lockdrop page](https://user-images.githubusercontent.com/71173976/92996254-8fd80b00-f50a-11ea-981e-cf9bb92e2ea4.JPG)
![Plasm account](https://user-images.githubusercontent.com/71173976/92996255-9070a180-f50a-11ea-812a-be4741543c39.JPG)

Hmmm...don't understand why I can't see the PLM. I attached two printscreens. I created an account via metamask private seed (same account as lockdrop). On the claim page it showed a default address. When clicking on the pencil my new account address showed. I claimed to the default address. I did not created a new account from the lockdrop page. Any idea how to access the address which now holds the PLM (b9uV2gn81w5pFsadFGbFMAcw837MGQkBXLNN6qgjCEn4Acb)?

**Comment by Majosk100** [comment] 2020-09-12 13:19
Ah wait, it has been sent to my metamask address. Cant see or transfer it from there, am I right?

**Comment by hoonsubin** [comment] 2020-09-12 13:31
if you are using a hardware wallet and you are accessing the site via MetaMask, you cannot access your funds at this time. But you should still be able to view the number of funds you have (assuming you are using the correct plasm network address).
You will have to wait until this gets finished https://medium.com/stake-technologies/stake-technologies-received-a-web3-open-grant-from-web3-foundation-d26f4b7fc3e0 for accessing funds I'm afraid

**Comment by Majosk100** [comment] 2020-09-12 13:46
Thanks for the help thusfar. sorry to bother you.
But Im a bit worried. It wasnt sent to my metamask, nor ledger but to the default address:
 b9uV2gn81w5pFsadFGbFMAcw837MGQkBXLNN6qgjCEn4Acb (see also print screen). I thought this was an address linked to eth lock address (on metamask in my case). You can see the print screen from the instruction. So how can I access the PLM?
![PLASM lockdrop and claim page](https://user-images.githubusercontent.com/71173976/92996854-07a83480-f50f-11ea-9d71-a943485b5143.JPG)
![Plasm lockdrop instruction](https://user-images.githubusercontent.com/71173976/92996855-0840cb00-f50f-11ea-9aaa-2b153cf7b798.JPG)

**Comment by hoonsubin** [comment] 2020-09-12 13:54
Your default address IS your ledger/metamask. That is how it was generated. This article may help you if you haven't read it yet https://medium.com/stake-technologies/lockdrop-the-hitchhikers-guide-to-plasm-network-token-distribution-38299e14d5d4

**Comment by Majosk100** [comment] 2020-09-13 09:10
Hi Hoon Kim,
Yeah I read that article, also your "hitchhikers guide", which was very helpful. Yet, for some reason I can't see my claimed PLM in my Plasm account. I have used the metamask private key to set up the account (raw seed, ECDSA) but no PLM. Tried it a couple times now. Even after reading your articles its unclear to me where my PLM went (except for seeing it via the plasm explorer) or how to access it. Any ideas left?
KR. René

**Comment by hoonsubin** [comment] 2020-09-13 09:54
@Majosk100 For accessing your funds that were sent to your hardware wallet, the only thing we can do now is to wait until the MM hardware wallet integration with Plasm network tokens are completed. I have checked the balance of your default plasm address (i.e. the one that's "in" your Ledger device) and it shows the correct amount of balance https://plasm.subscan.io/account/b9uV2gn81w5pFsadFGbFMAcw837MGQkBXLNN6qgjCEn4Acb

You have successfully claimed your lockdrop reward tokens and as long as you don't lose your ledger device, I do not see the reason why you should be worried.

**Comment by Majosk100** [comment] 2020-09-13 10:10
Alright, thanks for the quick response, once more. I think the misunderstanding originates from the term "hardware wallet". I originally connected my nano S to metamask to join the lockdrop. That, however, did not work (got an error for which we got in contact on discord). So I transferred my eth to metamask directly and joined the lockdrop from Metamask address instead. So, does waiting for the hardware wallet integration (ledger, trezor etc) make any difference in my case?

**Comment by hoonsubin** [comment] 2020-09-13 10:47
thank you for clearing up my misunderstanding. So to get this straight, the address that you used was an address made from MM and not Ledger, meaning that the address `b9uV2gn81w5pFsadFGbFMAcw837MGQkBXLNN6qgjCEn4Acb` is not your Ledger address, but from your MM account that you made, is this correct?

In either case, the system has confirmed that your funds have been received to your address so as long as you don't lose access to this MM address, you are fine. Furthermore, waiting for the MM extension implementation for Plasm network will solve your issue as it allows you to view and make Plasm network transaction directly from MM. But if you still want to access your funds, follow this guide to view your private key for the account that you used to lock the tokens https://metamask.zendesk.com/hc/en-us/articles/360015289632-How-to-Export-an-Account-Private-Key
then make a new address from here https://apps.plasmnet.io/#/accounts and paste the exported MM account private key as the seed (don't forget to put the `0x` prefix when pasting it).

I understand that you have already gone through this process to import your Ethereum keys, **but from the address displayed on the above screenshot, it seems that you have imported a different private key**. So to solve your issue, first, you have to tell me where `b9uV2gn81w5pFsadFGbFMAcw837MGQkBXLNN6qgjCEn4Acb` came from, is it the default address of your Ledger? MM account? or a new address made from plasm apps portal.

This part is hard for me to provide support without having access to your private keys (and you should never give them out). One way to make things clear is by listing all the Plasm network address that you have used for the lockdrop and tell me where it came from (ex: Ledger, MM default address, or a new address made from plasm app portal, etc.)

**Comment by Majosk100** [comment] 2020-09-13 13:01
Hi Hoon Kim,
_thank you for clearing up my misunderstanding. So to get this straight, the address that you used was an address made from MM and not Ledger, meaning that the address b9uV2gn81w5pFsadFGbFMAcw837MGQkBXLNN6qgjCEn4Acb is not your Ledger address, but from your MM account that you made, is this correct?_ YES

_In either case, the system has confirmed that your funds have been received to your address so as long as you don't lose access to this MM address_   True, although b9uV2gn81w5pFsadFGbFMAcw837MGQkBXLNN6qgjCEn4Acb is not my MM address. My MM address is 0xA1E8260f024ecA7E571bd09B21d71372FDeb5A21 and my nano ledger address is 0xD56D92C93a3e549c42963f4e6395b709CE0E4a32. 

So I do not know where that default address came from...Weird thing is that when Im on the lockdrop page, connected to MM, I see the printscreen I attached. That address matches my Plasm account address (0xa2XmZJ77QvWaCuyDDeALe3SyNZ95V4beDbihYyGVktzFry7). But its not the default address. 

I have checked previous transactions on MM. Cant see that 0xb9uV2gn81w5pFsadFGbFMAcw837MGQkBXLNN6qgjCEn4Acb anywhere...

My Claim ID: 0xe4a1506f5c6d7fff1f4a82c38c480855cc6dadbdcdebd4a61e82519f1bf327b6
![lockdrop page](https://user-images.githubusercontent.com/71173976/93018710-efe5b480-f5d1-11ea-9aef-a92c8026eaae.JPG)

**Comment by hoonsubin** [comment] 2020-09-14 05:03
unfortunately, if you don't know which address you used for claiming your lockdrop rewards, it is hard for me to provide support to you. If you have made a new address from Plasm network portal, don't lose them, and don't lose your other ethereum address as well as those are the only way you can access your funds.

**Comment by hoonsubin** [comment] 2020-09-14 05:31
this is your lockdrop information
```
{
  params: {
    type: 1,
    transaction_hash: 0x3e676d1cac06d11dd40916225398ca380ff14801b173933b8ee76ba9db257460,
    public_key: 0x03e43893789a24fe7bf221d15dcb13f4108688ef88a65fcfc234137205cfbcdd8b,
    duration: 25,920,000,
    value: 10,000,000,000,000,000,000
  },
  approve: [
    Vx4tqetqK5vtz9iUtgd4oBW2wKSiDx47UwmF8gi3wKq9GtK,
    WFjqjQ8HgjAR7qVe6KQggjvvRFSRL5w2jd2RMVXpCQaxikR,
    XDEZEWose6S3c4oeknNQstypUPyaKPPtYVc8Kf21gNCCC65,
    YJoxtWD84tC9rT6qMRc42eD2L2EKHcET8fcaovJ5TVun991,
    YLR6EQE8YZniK7YaaWcwMYh1qpuGTJpxuLhqQ6WPbN5Kz8m,
    b6ZLzdBKdx2ABPxCXLc7qRujxjvJt4pgKTderkAYRgASKzL
  ],
  decline: [],
  amount: 594,000,000,000,000,000,000,
  complete: true
}
```
and your lock transaction https://etherscan.io/tx/0x3e676d1cac06d11dd40916225398ca380ff14801b173933b8ee76ba9db257460

This shows me that you have sent the lock from `0xa1e8260f024eca7e571bd09b21d71372fdeb5a21` (with the public key of 0x03e43893789a24fe7bf221d15dcb13f4108688ef88a65fcfc234137205cfbcdd8b) and claimed it with `b9uV2gn81w5pFsadFGbFMAcw837MGQkBXLNN6qgjCEn4Acb` (which has the public key of `0xe6ca9335a7ce5313ad6f3a6a164ef7f0e745d039069f24fbd1132b1f75881e3f`). Please check all of your plasm addresses.

**Comment by Majosk100** [comment] 2020-10-14 19:13
Hi Hoon Kim,
Been a while. My apologies. I had some personal circumstances which required priority. I see there are only 6 days left for claiming so wanted to make sure I am not missing something. 

I went through my Plasm accounts. I only have two. Both created from MM, using my private key. The plasm address is a2XmZJ77QvWaCuyDDeALe3SyNZ95V4beDbihYyGVktzFry7 (see print screen - no PLM). 0xa1e8260f024eca7e571bd09b21d71372fdeb5a21 is my MM address, used for the lock drop. 

The b9uV2gn81w5pFsadFGbFMAcw837MGQkBXLNN6qgjCEn4Acb address still eludes me. I do not know where it came from or why my claimed PLM went to that address. I also do not see that address currently, when I access the lock drop page. I did see it a month ago, but I now see the address which should have received the PLM (...Fry7), which is weird (see print screens). 

Is it possible for me to create a new PLM account from that address (...Acb), with my MM private key? Any other solutions?
I'm a bit worried still...

![2020 09 12 PLASM lockdrop and claim page](https://user-images.githubusercontent.com/71173976/96034450-d8fce100-0e61-11eb-8966-eecea943a6dd.JPG)
![2020 10 14 PLM lockdrop claim overview](https://user-images.githubusercontent.com/71173976/96034454-d9957780-0e61-11eb-9956-19ba774a7069.JPG)
![account not found on plasm scan](https://user-images.githubusercontent.com/71173976/96034456-da2e0e00-0e61-11eb-8c21-6ae27e1ef962.JPG)
![PLM default address](https://user-images.githubusercontent.com/71173976/96034457-da2e0e00-0e61-11eb-8b71-418987e6bfd2.JPG)

**Comment by Majosk100** [comment] 2020-10-14 19:21
HE! I found it...for some reason, even though I transferred my ETH to MM from my ledger, before executing the lockdrop, it send it to the ledger. I see the print screen, when opening the lock drop page with MM using my nanno ledger S account.
So how do I access my PLM?

![MM ledger account](https://user-images.githubusercontent.com/71173976/96035315-29287300-0e63-11eb-9436-4280d8e027a9.JPG)

**Comment by Majosk100** [comment] 2020-10-14 19:22
It says I have no locks on it...

**Comment by hoonsubin** [comment] 2020-10-15 04:57
Access to Plasm Net accounts that derives from hardware wallets can only be done via our upcoming MetaMask support for Plasm address https://medium.com/stake-technologies/stake-technologies-received-a-web3-open-grant-from-web3-foundation-d26f4b7fc3e0
I'm afraid I will have to ask you to wait for a while and don't lose any of your keys.

**Comment by Majosk100** [comment] 2021-11-06 20:55
Hi Hoon Kim,

Its been a while...I had some issues with MM, also when trying to unlock my eth. Now I'd like to claim the PLM/ASTAR. Still having issues (see above). Do you have a manual/instrctions on how to?
KR. Majosk
